export const flashcards = [
  {
    id: "1",
    collectionId: "2",
    question: "What is the powerhouse of the cell?",
    answer: "The mitochondrion",
    isCorrect: false,
  },
  {
    id: "2",
    collectionId: "2",
    question: "What is the process by which plants make their food?",
    answer: "Photosynthesis",
    isCorrect: true,
  },
  {
    id: "3",
    collectionId: "2",
    question: "What are the building blocks of proteins?",
    answer: "Amino acids",
    isCorrect: false,
  },
  {
    id: "4",
    collectionId: "2",
    question: "What is the largest organ in the human body?",
    answer: "The skin",
    isCorrect: false,
  },
  {
    id: "5",
    collectionId: "2",
    question: "What is the main function of red blood cells?",
    answer: "To transport oxygen",
    isCorrect: false,
  },
  {
    id: "6",
    collectionId: "5",
    question: "What is the capital of France?",
    answer: "Paris",
    isCorrect: false,
  },
  {
    id: "7",
    collectionId: "5",
    question: "Which river is the longest in the world?",
    answer: "The Nile",
    isCorrect: false,
  },
];
